name: HBase-build-workflow
on: 
  push:
    branches: [ march-Action/2.4.14 ]
jobs:
  build-hbase:
    runs-on: ubuntu-20.04
    #https://github.com/actions/runner-images
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: rel/2.4.14
      - name: build hbase-2.4.14
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        run: |
          sudo lsb_release -a
          sudo uname -m
          sudo apt-get -y install openjdk-8-jdk
          sudo apt-get -y install maven
          mkdir ./myRelease
          mvn clean package assembly:single -DskipTests -Dhadoop.profile=3.0 -Dhadoop-three.version=3.3.1
      - name: check contents
        run: ls -al /home/runner/work/hbase/hbase/hbase-assembly/target/*.tar.gz
      - name: move assembly to release
        run: cp /home/runner/work/hbase/hbase/hbase-assembly/target/*.tar.gz ./myRelease/
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package_checknative1
          path: myRelease