name: HBase-build-workflow
on: 
  push:
    branches: [ march-Action/2.4.14 ]
jobs:
  build-hbase:
    runs-on: ubuntu-20.04
    #https://github.com/actions/runner-images
    steps:
      - name: Checkout tag rel/2.4.14
        uses: actions/checkout@v3
        with:
          ref: rel/2.4.14
      - name: check kernel version info  
        run: lsb_release -a && uname -a
      - name: install openjdk-8-jdk
        run: sudo apt-get -y install openjdk-8-jdk
        #run: echo $JAVA_HOME_8_X64 ' ==> JAVA_HOME= ' $JAVA_HOME
      - name: Show Maven version
        #run: sudo apt-get -y install maven
        run: mvn -version
      - name: build hbase-2.4.14 with Hadoop 3.3.1 and build the Tarballs
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        run: mvn clean package assembly:single -DskipTests -Dhadoop.profile=3.0 -Dhadoop-three.version=3.3.1
      - name: make folder for save assembly files
        run: mkdir ./myRelease
      - name: move Tarballs to release folder
        run: cp /home/runner/work/hbase/hbase/hbase-assembly/target/*.tar.gz ./myRelease/
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package_HBase-2.4.14-ServerClient
          path: ./myRelease/